/*****************************
GENERATED FILE DO NOT EDIT
******************************/

#define SET_RADIO_EQUIPMENT_IS_FPV_EN (1 << 0)
#define SET_RADIO_EQUIPMENT_IS_TM_EN (1 << 1)

#define SET_PARACHUTE_OUTPUT_IS_PARACHUTE_ARMED (1 << 0)
#define SET_PARACHUTE_OUTPUT_IS_PARACHUTE1_EN (1 << 1)
#define SET_PARACHUTE_OUTPUT_IS_PARACHUTE2_EN (1 << 2)

#define SET_DATA_LOGGING_IS_LOGGING_EN (1 << 0)

#define DUMP_FLASH_CHIP_DUMP_SD (1 << 0)
#define DUMP_FLASH_CHIP_DUMP_USB (1 << 1)

#define RETURN_RADIO_EQUIPMENT_IS_FPV_EN (1 << 0)
#define RETURN_RADIO_EQUIPMENT_IS_TM_EN (1 << 1)

#define RETURN_PARACHUTE_OUTPUT_IS_PARACHUTE_ARMED (1 << 0)
#define RETURN_PARACHUTE_OUTPUT_IS_PARACHUTE1_EN (1 << 1)
#define RETURN_PARACHUTE_OUTPUT_IS_PARACHUTE2_EN (1 << 2)

#define RETURN_DATA_LOGGING_IS_LOGGING_EN (1 << 0)

#define RETURN_DUMP_FLASH_DUMP_SD (1 << 0)
#define RETURN_DUMP_FLASH_DUMP_USB (1 << 1)
