
#define PIN_CAN_RX 0
#define PIN_CAN_TX 1
#define PIN_FPV_MOS 2
#define PIN_CAN_MOS 3
#define PIN_PYRO_2 4
#define PIN_PYRO_3 5
#define PIN_PYRO_4 6
#define PIN_TM_RX 7
#define PIN_TM_TX 8
#define PIN_TM_MOS 9
#define PIN_FLASH_CS 10
#define PIN_MOSI0 11
#define PIN_MISO0 12
#define PIN_SCL2 24
#define PIN_SDA2 25
#define PIN_MOSI1 26
#define PIN_SCK1 27
#define PIN_GPS_RX 28
#define PIN_GPS_TX 29
#define PIN_PYRO_6 30
#define PIN_PYRO_5 31
#define PIN_LIFTOFF 32
#define PIN_RF_INT 33
#define PIN_EXT_RX 34
#define PIN_EXT_TX 35
#define PIN_EXT_MOS 36
#define PIN_GPS_MOS 37
#define PIN_RF_RESET 38
#define PIN_MISO1 39
#define PIN_RF_CS 40
#define PIN_PYRO_EN 41
#define PIN_SCK0 13
#define PIN_FPV_RX 14
#define PIN_FPV_TX 15
#define PIN_RGB_TX 17
#define PIN_SDA0 18
#define PIN_SCL0 19
#define PIN_EXT1_TX 20
#define PIN_EXT1_RX 21
#define PIN_PYRO_1 22
#define PIN_BUZZER 23

#define TM_SERIAL Serial2
#define SPI_FLASH SPI1
#define SPI_RADIO SPI
#define GPS_SERIAL Serial7
#define EXT_SERIAL Serial8
#define FPV_SERIAL Serial3
#define RGB_SERIAL Serial4
#define EXT1_SERIAL Serial5

#define RFM_FREQUENCY 433
#define RFM_POWER 13